In [8]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat
import scienceplots

plt.style.use(['science','notebook'])

In [28]:
t0 = 0
tau_e = 2
E = 5
print(np.arange(t0,t0+tau_e*E,tau_e))

[0 2 4 6 8]


In [26]:
subjects = (['03CM','04ML','05NK','06AT','07YC','08RD','09NT','10EM','11AD','12AD',
             '13AB','14LS','15AC','16AG','17SM','18NB','19LS','20FC','21AB','22RT','23ST'])
print(f"Number of subjects: {len(subjects)}")

Number of subjects: 21


In [27]:
for subject in subjects:
    prova = loadmat(f"./TiBET/{subject}_filled_offset.mat")
    print(prova['mat'].shape) # (62, 551, 149): elettrodi, time point (1000 Hz: 1 ms), variable trials
                              # P1 <-> FC1
                              # primi 50 pti: baseline
                              # poi altri 50 usati per baseline
                              # t0=100

(62, 551, 149)
(62, 551, 148)
(62, 551, 150)
(62, 551, 149)
(62, 551, 145)
(62, 551, 150)
(62, 551, 149)
(62, 551, 150)
(62, 551, 149)
(62, 551, 149)
(62, 551, 140)
(62, 551, 139)
(62, 551, 150)
(62, 551, 150)
(62, 551, 144)
(62, 551, 150)
(62, 551, 150)
(62, 551, 150)
(62, 551, 150)
(62, 551, 144)
(62, 551, 148)


In [37]:
t0 = 100
tau_e = 1
E = 5
window_t0 = np.arange(t0, t0+tau_e*E, tau_e) #  E time-points between t0 and t0 + (E-1)*tau_e
prova['mat'][0,window_t0+551-t0-E,0]

array([-5.55961157, -4.46387152, -3.37322857, -2.28010399, -1.17842589])

In [24]:
prova['mat'][1]

array([[ 18.37372817,  -1.51538617,   4.88810263, ..., -36.83146872,
          8.57122149,  15.61556964],
       [ 17.78031269,  -2.84475664,   4.43349214, ..., -35.48192283,
         11.53649252,  15.56080296],
       [ 17.17068792,  -4.13128194,   4.06234838, ..., -33.46845381,
         14.12777742,  15.29741081],
       ...,
       [  8.1466118 ,  -3.79946731,  13.33939909, ...,  21.75062857,
         -0.7652334 ,  16.37147471],
       [  9.6187157 ,  -3.72297956,  14.14328565, ...,  22.36781536,
         -0.81579237,  15.13556402],
       [ 11.32175675,  -3.64417234,  14.96938128, ...,  23.22104124,
         -1.27366047,  13.89107245]])

7.45

In [1]:
import pandas as pd
electrodes = pd.read_csv("./TiBET/electrodes.csv", header=None)

In [16]:
prova = electrodes.to_numpy(dtype=str).flatten()
print(prova)
np.where(prova=='Oz')[0][0]

['Fp1' 'Fp2' 'F3' 'F4' 'C3' 'C4' 'P3' 'P4' 'O1' 'O2' 'F7' 'F8' 'T7' 'T8'
 'P7' 'P8' 'Fz' 'FCz' 'Cz' 'Pz' 'FC1' 'FC2' 'CP1' 'CP2' 'FC5' 'FC6' 'CP5'
 'CP6' 'TP9' 'TP10' 'F1' 'F2' 'C1' 'C2' 'P1' 'P2' 'AF3' 'AF4' 'FC3' 'FC4'
 'CP3' 'CP4' 'PO3' 'PO4' 'F5' 'F6' 'C5' 'C6' 'P5' 'P6' 'AF7' 'AF8' 'FT7'
 'FT8' 'TP7' 'TP8' 'PO7' 'PO8' 'Fpz' 'CPz' 'POz' 'Oz']


61

In [3]:
data = {}
data_processed = {}

for subject in subjects:
    print("Subject " + str(subject) + ": ")
    for duration in durations:
        data[subject,duration] = loadmat("dada_dataset/sub-"+str(subject)+"_task-baseline_duration-"+str(duration)+".mat")

        # preprocess: detrending + baseline subtraction computing mean as in https://doi.org/10.1016/j.cub.2022.08.006 
        # (window of half-size 50 ms (12 points) around offset)
        data_processed[subject,duration] = detrend(data[subject,duration]['eeg_data'][:,:,:], axis=1, type='linear')
        data_processed[subject,duration] -= np.mean(data_processed[subject,duration][:,50-12:50,:], axis=1)[:,np.newaxis,:]

        print("Duration {:d}: ".format(duration), data[subject,duration]['eeg_data'].shape)
    print("\n")
metadata = {}
for subject in subjects:
    for duration in durations:
        metadata[subject,duration] = pd.read_csv("dada_dataset/sub-"+str(subject)+"_task-baseline_duration-"+str(duration)+".csv")
    

SyntaxError: invalid syntax (2117386916.py, line 1)